#!/bin/bash
if [ "x$1" == "x" ]; then
	echo "Usage: $0 <version>"
	exit 1;
elif [ $(git tag -l | grep "v$1") ]; then
	git archive --format=tar --prefix=opendsme-$1/ v$1 |
		gzip >opendsme-$1.tar.gz;
else
	echo "No tag v$1 found"
	exit 1
fi
